webtalk_init -webtalk_dir F:/FPGA/Basys3/project/10_Dynamic_seg_display/prj/Dynamic_seg_display.sim/sim_1/behav/xsim/xsim.dir/Dynamic_seg_display_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 23 20:21:29 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ccd8e284-50c2-4385-85b3-f30d0390f8b5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "399ec90ab3894a1ca6e475bfe3130de8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2295 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2520 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.23_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8136_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2414338674 -regid "" -xml F:/FPGA/Basys3/project/10_Dynamic_seg_display/prj/Dynamic_seg_display.sim/sim_1/behav/xsim/xsim.dir/Dynamic_seg_display_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/FPGA/Basys3/project/10_Dynamic_seg_display/prj/Dynamic_seg_display.sim/sim_1/behav/xsim/xsim.dir/Dynamic_seg_display_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/FPGA/Basys3/project/10_Dynamic_seg_display/prj/Dynamic_seg_display.sim/sim_1/behav/xsim/xsim.dir/Dynamic_seg_display_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
